name = "glow-helius-rpc-proxy"
main = "./src/index.ts"
compatibility_date = "2022-05-03"

[env.dev.route]
pattern = "rpc.shinylab.xyz"
custom_domain = true

[env.dev.vars]
ENVIRONMENT = "dev"
CORS_ALLOW_ORIGIN = "https://app.dev.shinylab.xyz,https://app.staging.shinylab.xyz,http://localhost:3000"
NETWORK = "devnet"

[env.prod.route]
pattern = "rpc.glowfinance.xyz"
custom_domain = true

[env.prod.vars]
ENVIRONMENT = "prod"
CORS_ALLOW_ORIGIN = "https://app.glowfinance.xyz,https://app.preprod.shinylab.xyz"
NETWORK = "mainnet"